import AudioFiles from "./AudioFiles.js"
import AudioSystemEqualizer from "./AudioSystemEqualizer.js"
import CDPlayer from "./CDPlayer.js"
import EarpodsAirpods from "./EarpodsAirpods.js"
import Headphones from "./Headphones.js"
import IPodDigitalPlayers from "./IPodDigitalPlayers.js"
import Microphone from "./Microphone.js"
import ModernMusic from "./ModernMusic.js"
import Music from "./Music.js"
import MusicGenres from "./MusicGenres.js"
import MusicInstruments from "./MusicInstruments.js"
import Playlists from "./Playlists.js"
import Podcasts from "./Podcasts.js"
import Radios from "./Radios.js"
import Speakers from "./Speakers.js"
import VinylRecords from "./VinylRecords.js"
import VolumeControls from "./VolumeControls.js"
import WalkmanTapes from "./WalkmanTapes.js"

export default { AudioFiles, AudioSystemEqualizer, CDPlayer, EarpodsAirpods, Headphones, IPodDigitalPlayers, Microphone, ModernMusic, Music, MusicGenres, MusicInstruments, Playlists, Podcasts, Radios, Speakers, VinylRecords, VolumeControls, WalkmanTapes }